services:
  beacontelemetryhub.host:
    image: ${DOCKER_REGISTRY-}beacontelemetryhubhost
    container_name: beacontelemetryhubhost
    privileged: true
    restart: always
    user: root
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev 
      - /sys:/sys
    environment:
      - BeaconTelemetryHubSettings__AdapterName=/org/bluez/hci0
      - Serilog__MinimumLevel=Debug
      - 'UDEV=1' 
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}      
    network_mode: "host"
    build:
      context: .
      dockerfile: BeaconTelemetryHub.Host/Dockerfile
    depends_on:
        - db
  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    container_name: grafana 
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    depends_on:
      - db
  db:
    image: yobasystems/alpine-mariadb
    container_name: mariadb 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD} 
      - MYSQL_DATABASE=beacons_data 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
   db_data:
   grafana_storage: 