services:
  beacontelemetryhub.host:
    image: ${DOCKER_REGISTRY-}beacontelemetryhubhost
    container_name: beacontelemetryhubhost
    privileged: true
    user: root
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev 
      - /sys:/sys
    environment:
      - BeaconReceiverSettings__AdapterName=/org/bluez/hci0
      - Serilog__MinimumLevel=Debug
      - 'UDEV=1'
    network_mode: "host"
    build:
      context: .
      dockerfile: BeaconTelemetryHub.Host/Dockerfile
      
  nocodb:
        image: nocodb/nocodb:latest
        container_name: nocodb-csv
        ports:
            - "8080:8080"
        volumes:
            - noco_data:/usr/app/data
        restart: always

volumes:
   noco_data: