services:
  estimotebeaconreceiver:
    image: ${DOCKER_REGISTRY-}estimotebeaconreceiver
    privileged: true
    user: root
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev 
      - /sys:/sys
    environment:
      - BeaconReceiverSettings__AdapterName=/org/bluez/hci0
      - BeaconReceiverSettings__EstimoteServiceUUID=fe9a
      - BeaconReceiverSettings__EstimoteTelemetryPacketTypeId=0x02
      - 'UDEV=1'
    network_mode: "host"
    build:
      context: EstimoteBeaconReceiver
      dockerfile: Dockerfile
