services:
  beacontelemetryhub:
    image: ${DOCKER_REGISTRY-}beacontelemetryhub
    privileged: true
    user: root
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev:/dev 
      - /sys:/sys
    environment:
      - BeaconReceiverSettings__AdapterName=/org/bluez/hci0
      - BeaconReceiverSettings__EstimoteServiceUUID=fe9a
      - BeaconReceiverSettings__EstimoteTelemetryPacketTypeId=0x02
      - 'UDEV=1'
    network_mode: "host"
    build:
      context: BeaconTelemetryHub.Receiver
      dockerfile: Dockerfile
  nocodb:
    image: nocodb/nocodb:latest
    container_name: nocodb-csv
    ports:
      - "8080:8080"
    volumes:
      - noco_data:/usr/app/data
    restart: always
volumes:
    noco_data:

     
